let coffeeshopsData = [
  {
    id: 1,
    name: "Dazbog Coffee",
    img: "https://example.com/path-to-image.jpg",
    address: "1201 E 9th Ave, Denver, CO 80218",
    rating: 4.3,
    hours: {
      "Monday-Friday": "6:00am - 4:00pm",
      "Saturday-Sunday": "7:00am - 5:00pm",
    },
    phoneNumber: "303-837-1275",
    website: "https://dazbog.com",
    foodProvided: true,
    dineIn: true,
    takeOut: true,
    wheelchairAccessible: true,
  },
  {
    id: 2,
    name: "La Colombe Coffee Roasters",
    img: "https://example.com/path-to-image.jpg",
    address: "900 E 11th Ave, Denver, CO 80218",
    rating: 3.4,
    hours: {
      "Monday-Friday": "7:00am - 5:00pm",
      "Saturday-Sunday": "7:00am - 5:00pm",
    },
    phoneNumber: "720-643-1750",
    website: "https://www.wholefoodsmarket.com",
    foodProvided: true,
    dineIn: true,
    takeOut: true,
    wheelchairAccessible: true,
  },
  {
    id: 3,
    name: "Pablos Coffee",
    img: "https://example.com/path-to-image.jpg",
    address: "1300 Pennsylvania St Ste 102, Denver, CO 80203",
    rating: 4.5,
    hours: {
      "Monday-Friday": "7:00am - 2:00pm",
      "Saturday-Sunday": "7:00am - 2:00pm",
    },
    phoneNumber: "303-832-1688",
    website: "https://pabloscoffee.com",
    foodProvided: true,
    dineIn: true,
    takeOut: true,
    wheelchairAccessible: true,
  },
  {
    id: 4,
    name: "Roostercat Coffee House",
    img: "https://example.com/path-to-image.jpg",
    address: "1045 Lincoln St, Denver, CO 80203",
    rating: 4.5,
    hours: {
      "Monday-Thursday": "7:00am - 6:00pm",
      "Friday-Saturday": "7:00am - 8:00pm",
    },
    phoneNumber: "720-388-0356",
    website: "https://roostercatdenver.com",
    foodProvided: true,
    dineIn: true,
    takeOut: true,
    wheelchairAccessible: true,
  },
  {
    id: 5,
    name: "Sky Tea (Drip Denver)",
    img: "https://example.com/path-to-image.jpg",
    address: "955 Lincoln St G, Denver, CO 80203",
    rating: 4.6,
    hours: {
      "Monday-Saturday": "7:30am - 8:00pm",
      Sunday: "8:00am - 7:00pm",
    },
    phoneNumber: "303-832-0482",
    website: "https://dripdenver.com",
    foodProvided: true,
    dineIn: true,
    takeOut: true,
    wheelchairAccessible: true,
  },
  {
    id: 6,
    name: "Starbucks Coffee",
    img: "https://example.com/path-to-image.jpg",
    address: "2150 S Downing St, Denver, CO 80210",
    rating: 4.1,
    hours: {
      "Monday-Friday": "6:00am - 7:00pm",
      "Saturday-Sunday": "6:00am - 7:00pm",
    },
    phoneNumber: "303-722-6117",
    website: "https://starbucks.com",
    foodProvided: true,
    dineIn: true,
    takeOut: true,
    wheelchairAccessible: true,
  },
  {
    id: 7,
    name: "The Network Coffee House",
    img: "https://example.com/path-to-image.jpg",
    address: "1402 Pearl St, Denver, CO 80203",
    rating: 4.1,
    hours: {
      Monday: "6:00am - 9:00pm",
      Tuesday: "10:00am - 2:00pm, 6:00pm-9:00pm",
      Wednesday: "6:00am - 9:00pm",
      Thursday: "10:00am - 2:00pm, 6:00-9:00pm",
      Friday: "Closed",
      Saturday: "6:30am - 10:00am",
      Sunday: "Closed",
    },
    phoneNumber: "303-830-1508",
    website: "https://networkcoffeehouse.org",
    foodProvided: false,
    dineIn: true,
    takeOut: true,
    wheelchairAccessible: true,
  },
  {
    id: 8,
    name: "Thump Coffee",
    img: "https://example.com/path-to-image.jpg",
    address: "1201 E 13th Ave, Denver, CO 80218",
    rating: 4.5,
    hours: {
      "Monday-Friday": "6:00am - 5:00pm",
      "Saturday-Sunday": "6:00am - 5:00pm",
    },
    phoneNumber: "720-456-6648",
    website: "https://thumpcoffee.com",
    foodProvided: true,
    dineIn: true,
    takeOut: true,
    wheelchairAccessible: true,
  },
];

module.exports = coffeeshopsData;
